# Generated by Django 3.2 on 2021-05-15 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eng_quiz_topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='eng_quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('no_of_questions', models.IntegerField(blank=True, null=True)),
                ('pass_score', models.IntegerField(blank=True, help_text='合格分數', null=True)),
                ('time', models.IntegerField(help_text='Quiz時間')),
                ('difficulty', models.IntegerField(choices=[(1, 'K1'), (2, 'K2'), (3, 'K3'), (11, 'P1'), (12, 'P2'), (13, 'P3')], max_length=6)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_eng.eng_quiz_topic')),
            ],
        ),
        migrations.CreateModel(
            name='eng_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_eng.eng_quiz')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_eng.eng_quiz_topic')),
            ],
        ),
        migrations.CreateModel(
            name='eng_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('correct', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_eng.eng_question')),
            ],
        ),
    ]
