# Generated by Django 3.2 on 2021-05-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn_eng', '0002_auto_20210516_0139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eng_question',
            options={'verbose_name_plural': 'English Questions'},
        ),
        migrations.AlterModelOptions(
            name='eng_quiz',
            options={'verbose_name_plural': 'English Quizes'},
        ),
        migrations.AlterModelOptions(
            name='eng_quiz_topic',
            options={'verbose_name_plural': 'English Topics'},
        ),
    ]
