# Generated by Django 3.2 on 2021-05-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_eng', '0003_auto_20210519_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='eng_question',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='eng_quiz'),
        ),
        migrations.AddField(
            model_name='eng_quiz',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='題目內容'),
        ),
        migrations.AddField(
            model_name='eng_quiz',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='eng_quiz'),
        ),
    ]
