# Generated by Django 3.2 on 2021-05-30 09:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learn_eng', '0004_auto_20210530_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='eng_vocab_topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'English Vocabulary Topic',
            },
        ),
        migrations.RenameField(
            model_name='eng_answer',
            old_name='created',
            new_name='created_time',
        ),
        migrations.AddField(
            model_name='eng_answer',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eng_question',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eng_quiz',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eng_quiz_topic',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eng_quiz_topic',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='eng_vocab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab', models.CharField(max_length=200)),
                ('difficulty', models.IntegerField(choices=[(1, 'K1'), (2, 'K2'), (3, 'K3'), (11, 'P1'), (12, 'P2'), (13, 'P3')])),
                ('picture', models.ImageField(blank=True, null=True, upload_to='eng_quiz')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_eng.eng_quiz_topic')),
            ],
            options={
                'verbose_name_plural': 'English Vocabulary',
            },
        ),
    ]
