# Generated by Django 3.2 on 2021-05-30 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn_eng', '0006_alter_eng_vocab_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eng_vocab',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learn_eng.eng_vocab_topic'),
        ),
    ]
