# Generated by Django 3.2 on 2021-05-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_profile_picuture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eng_question_result',
            options={'verbose_name_plural': 'English Question Results'},
        ),
        migrations.AlterModelOptions(
            name='eng_quiz_result',
            options={'verbose_name_plural': 'English Quiz Results'},
        ),
        migrations.AlterModelOptions(
            name='redeem',
            options={'verbose_name_plural': 'Redeem Record'},
        ),
        migrations.AlterModelOptions(
            name='redeem_type',
            options={'verbose_name_plural': 'Redeem Type'},
        ),
        migrations.AlterModelOptions(
            name='user_profile',
            options={'verbose_name_plural': 'User Profile'},
        ),
        migrations.AddField(
            model_name='redeem',
            name='content',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
