# Generated by Django 3.2 on 2021-05-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_redeem_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='picuture',
            new_name='picture',
        ),
    ]
