# Generated by Django 3.2 on 2021-05-27 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210520_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eng_question_result',
            name='no_correct',
        ),
        migrations.RemoveField(
            model_name='eng_question_result',
            name='no_total',
        ),
        migrations.AddField(
            model_name='eng_question_result',
            name='answer_correct',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='eng_question_result',
            name='answer_selected',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='eng_question_result',
            name='correct',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eng_question_result',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.eng_quiz_result'),
        ),
    ]
