# Generated by Django 3.2 on 2021-05-27 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_eng_quiz_result_quiz_pass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eng_question_result',
            old_name='time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='eng_quiz_result',
            old_name='time',
            new_name='create_time',
        ),
    ]
