# Generated by Django 3.2 on 2021-05-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210527_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eng_question_result',
            options={'verbose_name_plural': 'English Quiz Question Results'},
        ),
        migrations.AlterField(
            model_name='eng_question_result',
            name='correct',
            field=models.IntegerField(blank=True, choices=[(0, 'N'), (1, 'Y')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eng_quiz_result',
            name='quiz_pass',
            field=models.IntegerField(blank=True, choices=[(0, 'N'), (1, 'Y')], default=0, null=True),
        ),
    ]
