# Generated by Django 3.2 on 2021-05-30 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210530_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eng_quiz_result',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.AddField(
            model_name='redeem',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redeem_type',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redeem_type',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
