# Generated by Django 3.2 on 2021-05-30 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_eng_vocab_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='family',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.user_profile'),
        ),
    ]
